---
title: "R Notebook"
output: html_notebook
---
# Tp1, Pregunta 2: 

```{r}
library(quantreg);
library(readxl); # para leer archivos xml, pero vamos a usar el paquete eph
#library(eph);
library(dplyr);
library(tidyr)
library(ggplot2)
```

Mismas especificaciones de la pregunta 1: 

```{r}
#base2024 <- get_microdata(year = 2024) # para leer usando el paquete eph 
base2024 <- read_excel('EPH_usu_1er_Trim_2024_xlsx/usu_individual_T124.xlsx')

base2024 <- base2024[base2024$P21>0 &      ## asalariados
                       base2024$CH03 == 01 & ## jefes de hogar
                       base2024$CH04 == 1 &  ## varones
                       25 <= base2024$CH06 & ## edades
                       base2024$CH06 <= 65,]
#1.a
anios_prev <- c(0, 0, 6, 6, 9, 12, 12, 18)
anios_post <- c(0, 6, 9, 12, 12, 15, 18, 22)

base2 <- base2024 %>%
  mutate(
    # Asignar el número de años en base al nivel de educación y condición de finalización
    anios_educacion = ifelse(CH13 == 1,
                      anios_post[CH12 + 1],  # +1 para ajustar al índice en R
                      anios_prev[CH12 + 1] + as.numeric(CH14)),
    
    # Calcular la experiencia potencial y su cuadrado
    exp_pot = CH06 - anios_educacion - 6,
    exp_pot_2 = exp_pot^2
  )

base2 <- base2[complete.cases(base2[, c("exp_pot")]), ] # nos quitamos los na's.
base2 <- base2[! (base2$anios_educacion > 100),]
```









